
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aauuecbslidjegrbgkid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdXVlY2JzbGlkamVncmJna2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTkyNjUsImV4cCI6MjA2MTU5NTI2NX0.vB6OyFUwGQSpL8GDWIczqDzD0vf_qBhZ-ZXz7A2c8lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
